// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_room_reservation_backend.Data;

#nullable disable

namespace _2026_room_reservation_backend.Data.Migrations
{
    [DbContext(typeof(RoomContext))]
    [Migration("20260215120713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("_2026_room_reservation_backend.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nrp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2026-02-20",
                            FullName = "Budi Tabuti",
                            Nrp = "5025211000",
                            Purpose = "Rapat Koordinasi Projek",
                            RoomCode = "A-104",
                            SessionStatus = "Upcoming",
                            Status = "Approved",
                            Time = "10:00 - 12:00"
                        });
                });

            modelBuilder.Entity("_2026_room_reservation_backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A-101",
                            Status = "available"
                        },
                        new
                        {
                            Id = 2,
                            Code = "A-102",
                            Status = "available"
                        },
                        new
                        {
                            Id = 3,
                            Code = "A-103",
                            Status = "available"
                        },
                        new
                        {
                            Id = 4,
                            Code = "A-104",
                            Status = "available"
                        },
                        new
                        {
                            Id = 5,
                            Code = "A-105",
                            Status = "available"
                        },
                        new
                        {
                            Id = 6,
                            Code = "A-106",
                            Status = "available"
                        },
                        new
                        {
                            Id = 7,
                            Code = "B-101",
                            Status = "available"
                        },
                        new
                        {
                            Id = 8,
                            Code = "B-102",
                            Status = "available"
                        },
                        new
                        {
                            Id = 9,
                            Code = "B-103",
                            Status = "available"
                        },
                        new
                        {
                            Id = 10,
                            Code = "B-104",
                            Status = "available"
                        },
                        new
                        {
                            Id = 11,
                            Code = "B-105",
                            Status = "available"
                        },
                        new
                        {
                            Id = 12,
                            Code = "B-106",
                            Status = "available"
                        },
                        new
                        {
                            Id = 13,
                            Code = "C-101",
                            Status = "available"
                        },
                        new
                        {
                            Id = 14,
                            Code = "C-102",
                            Status = "available"
                        },
                        new
                        {
                            Id = 15,
                            Code = "C-103",
                            Status = "available"
                        },
                        new
                        {
                            Id = 16,
                            Code = "C-104",
                            Status = "available"
                        },
                        new
                        {
                            Id = 17,
                            Code = "C-105",
                            Status = "available"
                        },
                        new
                        {
                            Id = 18,
                            Code = "C-106",
                            Status = "available"
                        },
                        new
                        {
                            Id = 19,
                            Code = "D-101",
                            Status = "available"
                        },
                        new
                        {
                            Id = 20,
                            Code = "D-102",
                            Status = "available"
                        },
                        new
                        {
                            Id = 21,
                            Code = "D-103",
                            Status = "available"
                        },
                        new
                        {
                            Id = 22,
                            Code = "D-104",
                            Status = "available"
                        },
                        new
                        {
                            Id = 23,
                            Code = "D-105",
                            Status = "available"
                        },
                        new
                        {
                            Id = 24,
                            Code = "D-106",
                            Status = "available"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
